const $=id=>document.getElementById(id);
const state={master:JSON.parse(localStorage.getItem('inv_master')||'[]'),entries:JSON.parse(localStorage.getItem('inv_entries')||'[]'),scanning:false,stream:null,detector:null};
renderEntries();renderSummary();updateProductInfo('');
$('masterFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;const t=await f.text();const lines=t.split(/\r?\n/).filter(x=>x.trim().length);const header=lines.shift().split(',').map(h=>h.trim().toLowerCase());const iName=header.findIndex(h=>['tên sản phẩm','ten san pham','name','ten'].includes(h));const iBarcode=header.findIndex(h=>['mã vạch','ma vach','barcode','ean','upc'].includes(h));const iSku=header.findIndex(h=>['mã hàng','ma hang','sku','code'].includes(h));const arr=[];for(const line of lines){const parts=parseCSV(line);const name=parts[iName]||'';const barcode=(parts[iBarcode]||'').trim();const sku=(iSku>=0?parts[iSku]:'');if(barcode)arr.push({barcode,name,sku});}state.master=arr;localStorage.setItem('inv_master',JSON.stringify(arr));alert('Đã nạp danh mục: '+arr.length+' sản phẩm');});
$('downloadMaster').addEventListener('click',()=>{const s='Tên sản phẩm,Mã vạch,Mã hàng\nSỮA NUTI DÂU,20102010283,SUA_NUTI_DAU\nCoca Cola 1.5L,8935049501381,COCA_15L\nPepsi 1.5L,8934588013065,PEPSI_15L\n7UP 1.5L,8934588023064,7UP_15L\n';downloadText('master_sample.csv',s);});
$('scanBtn').addEventListener('click',startScan);$('stopScan').addEventListener('click',stopScan);$('barcodeInput').addEventListener('change',e=>updateProductInfo(e.target.value.trim()));$('addBtn').addEventListener('click',addEntry);$('exportBtn').addEventListener('click',exportCSV);$('clearBtn').addEventListener('click',()=>{if(confirm('Xóa dữ liệu kiểm kê (giữ danh mục)?')){state.entries=[];localStorage.removeItem('inv_entries');renderEntries();renderSummary();}});
function addEntry(){const barcode=$('barcodeInput').value.trim();if(!barcode)return alert('Nhập hoặc quét mã vạch');const prod=findProduct(barcode);const name=prod?.name||'';const ts=new Date().toISOString();const q1=toInt($('qtyFridge').value);const q2=toInt($('qtyShelf').value);const q3=toInt($('qtyStock').value);const sum=q1+q2+q3;state.entries.push({ts,barcode,name,qtyFridge:q1,qtyShelf:q2,qtyStock:q3,sum});localStorage.setItem('inv_entries',JSON.stringify(state.entries));renderEntries();renderSummary();$('qtyFridge').value=0;$('qtyShelf').value=0;$('qtyStock').value=0;$('barcodeInput').select();}
function exportCSV(){const head='Thời gian,Mã vạch,Tên sản phẩm,Tủ lạnh,Trên kệ,Trong kho,TỔNG\n';const lines=state.entries.map(r=>[r.ts,r.barcode,escCSV(r.name),r.qtyFridge,r.qtyShelf,r.qtyStock,r.sum].join(','));downloadText('kiemke_export.csv',head+lines.join('\n'));}
function renderEntries(){const tb=$('resultTable').querySelector('tbody');tb.innerHTML='';state.entries.slice().reverse().forEach((r,idx)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${fmt(r.ts)}</td><td>${r.barcode}</td><td>${esc(r.name)}</td><td>${r.qtyFridge}</td><td>${r.qtyShelf}</td><td>${r.qtyStock}</td><td><b>${r.sum}</b></td><td><button class="btn danger" data-i="${idx}">Xóa</button></td>`;tb.appendChild(tr);});tb.querySelectorAll('button[data-i]').forEach(b=>b.onclick=()=>{const rev=parseInt(b.dataset.i,10);const real=state.entries.length-1-rev;state.entries.splice(real,1);localStorage.setItem('inv_entries',JSON.stringify(state.entries));renderEntries();renderSummary();});}
function renderSummary(){const sums={};for(const r of state.entries){const key=r.name||r.barcode;sums[key]=(sums[key]||0)+(r.sum||0);}const tb=$('sumTable').querySelector('tbody');tb.innerHTML='';Object.entries(sums).sort((a,b)=>b[1]-a[1]).forEach(([name,total])=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(name)}</td><td><b>${total}</b></td>`;tb.appendChild(tr);});}
function updateProductInfo(code){const p=findProduct(code);$('productName').textContent=p?.name||'—';$('sku').textContent=p?.sku||'—';}
function findProduct(code){return state.master.find(x=>x.barcode==code);}function toInt(v){v=parseInt(v,10);return Number.isFinite(v)&&v>0?v:0;}function escCSV(s){if(s==null)return'';s=String(s);if(/[\",\\n]/.test(s))return '\"'+s.replace(/\"/g,'\"\"')+'\"';return s;}function esc(s){return (s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}function fmt(iso){const d=new Date(iso);return d.toLocaleString();}function downloadText(n,t){const blob=new Blob([t],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=n;a.click();URL.revokeObjectURL(a.href);}function parseCSV(line){const out=[];let cur='',inQ=false;for(let i=0;i<line.length;i++){const ch=line[i];if(inQ){if(ch=='\"'&&line[i+1]=='\"'){cur+='\"';i++;}else if(ch=='\"'){inQ=false;}else cur+=ch;}else{if(ch==','){out.push(cur);cur='';}else if(ch=='\"'){inQ=true;}else cur+=ch;}}out.push(cur);return out;}
async function startScan(){if(state.scanning)return;if(!('BarcodeDetector'in window)){alert('iOS có thể không hỗ trợ quét trực tiếp. Dùng đầu đọc barcode Bluetooth hoặc nhập tay.');return;}try{state.detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_e','qr_code','code_128','code_39']});}catch(e){alert('Không khởi tạo được BarcodeDetector: '+e);return;}let stream;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});}catch(e){alert('Không truy cập được camera: '+e);return;}state.scanning=true;state.stream=stream;const v=document.getElementById('video');v.srcObject=stream;await v.play();document.getElementById('videoWrap').classList.remove('hidden');requestAnimationFrame(scanLoop);}
async function scanLoop(){if(!state.scanning)return;try{const v=document.getElementById('video');const bmp=await createImageBitmap(v);const codes=await state.detector.detect(bmp);bmp.close();if(codes&&codes.length){const code=codes[0].rawValue;document.getElementById('barcodeInput').value=code;updateProductInfo(code);stopScan();document.getElementById('qtyFridge').focus();return;}}catch(e){}requestAnimationFrame(scanLoop);}
function stopScan(){state.scanning=false;document.getElementById('videoWrap').classList.add('hidden');if(state.stream){state.stream.getTracks().forEach(t=>t.stop());state.stream=null;}}
